# Generated by Django 3.2 on 2022-10-05 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='crdt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
